#!/usr/bin/env tsx
/**
 * Generate the EMPTY SET PLATE for a finish.
 *
 *   npx tsx art-pipeline/gen-plate.ts --finish chrome-allstar
 *
 * Why this exists: the approved finish backgrounds are basketball sets — a basketball
 * court is baked into the very image used as the visual reference. Every sport was
 * therefore generated by asking the model to fight that court, and for sports far from
 * an indoor court (golf, swimming, track) it lost and left the basketball lines behind.
 *
 * The plate is the same set with a clean unmarked floor. Approve it once per finish;
 * gen-backgrounds then references the plate instead of the basketball original, so a
 * sport only ever has lines ADDED to an empty floor.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { FINISHES, finishBySlug } from "./finishes.js";
import { generateImage, loadEnv, MODEL } from "./lib/gemini.js";
import { refFor } from "./lib/img.js";

loadEnv();
const argv = process.argv.slice(2);
const flag = (n: string, d = "") => {
  const i = argv.indexOf(`--${n}`);
  return i >= 0 && argv[i + 1] && !argv[i + 1].startsWith("--") ? argv[i + 1] : d;
};

const finishes = flag("finish") ? [finishBySlug(flag("finish"))!] : FINISHES;
mkdirSync("art-pipeline/out/plates", { recursive: true });

for (const f of finishes) {
  const prompt = [
    `Use the attached image as the exact art direction reference. Reproduce it exactly:`,
    `${f.material}.`,
    ``,
    `Change TWO things, and nothing else:`,
    ``,
    `1. REMOVE every sport marking from the floor. No court lines, no painted key, no`,
    `   three-point arc, no centre circle, no boundary tape — nothing.`,
    `   The floor becomes ${f.floor}, completely clean and unmarked, its reflections and`,
    `   material exactly as in the reference.`,
    ``,
    `2. REMOVE every piece of sports equipment from the venue — basketball hoops and`,
    `   backboards, goals, nets, posts, benches, apparatus, scoreboards. Whatever the`,
    `   equipment was standing in front of (seating, wall, structure) is revealed behind it,`,
    `   continuing naturally. The playing area is left completely bare.`,
    ``,
    `Everything else is identical: same structures, same materials, same lighting`,
    `direction, same camera height and perspective, same colour grade, same composition.`,
    ``,
    `Hard requirements:`,
    `- Vertical poster format, 2:3.`,
    `- Completely empty stage. No people, no props, no sports equipment of any kind.`,
    `- No text, letters, numbers, logos or watermarks.`,
    `- Photorealistic, sharp, print quality.`,
  ].join("\n");

  const r = await generateImage({ prompt, refs: [await refFor(f.ref)], aspectRatio: "2:3" });
  const out = `art-pipeline/out/plates/${f.slug}.png`;
  writeFileSync(out, r.image);
  writeFileSync(out.replace(/\.png$/, ".json"), JSON.stringify({ model: MODEL, ref: f.ref, prompt, generatedAt: new Date().toISOString() }, null, 2));
  console.log(`  ok  ${out}  (${(r.image.length / 1024) | 0} KB)`);
}
